### ISSUE TITLE
Mod menu crashes when opening the config GUI of mods using this library

### ISSUE THREAD

**Issue by colby-boucher** [The-Fireplace-Minecraft-Mods/Fireplace-Lib#28]
Specifically Survival Tweaks, Mob Rebirth and Home Campfire.

Granted, this might be an issue with Mod Menu itself rather than your mods, or just a specific version incompatability, but since it's only these mods crashing I figured I should start here.

The crash report for each is very similar but I'll provide one for each anyways, threw a little not in each specifying which mod I selected the config GUI for with each crash:

[crash-2021-09-10_11.52.52-client.txt](https://github.com/The-Fireplace-Minecraft-Mods/Fireplace-Lib/files/7145013/crash-2021-09-10_11.52.52-client.txt)
[crash-2021-09-10_11.55.45-client.txt](https://github.com/The-Fireplace-Minecraft-Mods/Fireplace-Lib/files/7145014/crash-2021-09-10_11.55.45-client.txt)
[crash-2021-09-10_11.56.26-client.txt](https://github.com/The-Fireplace-Minecraft-Mods/Fireplace-Lib/files/7145015/crash-2021-09-10_11.56.26-client.txt)

**Comment by The-Fireplace** [comment]
As a temporary workaround, try using Mod Menu 2.0.2

**Comment by The-Fireplace** [comment]
Can you post a full log, not just the crash reports?

**Comment by colby-boucher** [comment]
Right, sorry

[latest.log](https://github.com/The-Fireplace-Minecraft-Mods/Fireplace-Lib/files/7149678/latest.log)

**Comment by The-Fireplace** [comment]
You're right, this seems to be an issue with Fireplace Lib. I'm not sure exactly why yet, but it was failing to load the language files. I've improved the error handling so it shouldn't crash now, but I don't expect it to be fully fixed yet. Can you try again with version 5.7.1 and post the log from that?

**Comment by colby-boucher** [comment]
Right, it doesn't crash any more, but all text in the config GUI including the title starts with txt.config.fst.[whatever] rather than displaying properly

[latest.log](https://github.com/The-Fireplace-Minecraft-Mods/Fireplace-Lib/files/7150115/latest.log)

Edit: oooof I just realized I had a Forge mod in there somehow looking at the log, didn't affect this though

**Comment by The-Fireplace** [comment]
Fixed in 5.7.2
