### ISSUE TITLE
Fireplace Lib 6.0.5+1.17.1 crashes stand-alone server during start-up

### ISSUE THREAD

**Issue by gniftygnome** [The-Fireplace-Minecraft-Mods/Fireplace-Lib#34]
**Describe the bug**
I added Unforgiving Void (and therefore also Fireplace Lib to a mod pack I'm working on and the server crashes during start up.  The crash still happens if I remove Unforgiving Void but keep Fireplace Lib, and it happens with or without version 5.0.38 of Cloth Config.

**To Reproduce**

0. Install lots of mods.  If this issue is not obvious and you need me to bisect for a conflicting mod, let me know.
1. Install Fireplace Lib 6.0.5+1.17.1 (also  6.0.4+1.17.1 has the bug)
2. Start the server
3. Get the stack trace below and the server hangs

**Logs/Screenshots/Videos**
Log here: https://gist.github.com/gniftygnome/ff8e779428e7bbdc55ebd316bbb3f546

Crash cause in log:
Caused by: java.lang.RuntimeException: Cannot load class me.shedaniel.clothconfig2.impl.builders.FieldBuilder in environment type SERVER

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.17.1
 - Mod Version: 6.0.5+1.17.1
 - Fabric API: 0.40.1+1.17

**Comment by The-Fireplace** [comment]
I see. Give me a few minutes and I'll get it fixed.

**Comment by The-Fireplace** [comment]
Fixed in FL 6.0.6.

**Comment by gniftygnome** [comment]
Confirmed fixed.  Thanks!
