### ISSUE TITLE
cant use on 1.19.4

### ISSUE THREAD

**Issue by SouthernPixelYT** [The-Fireplace-Minecraft-Mods/Fireplace-Lib#58]
https://pastebin.com/M7411yK9 I figured it would be fine since its still in the 1.19 update line but it crashes when I try to open a book. Game launches fine though

**Comment by SouthernPixelYT** [comment]
<img width="189" alt="textbook" src="https://github.com/The-Fireplace-Minecraft-Mods/Fireplace-Lib/assets/105022650/2192ef45-625f-4e21-9bfb-0d8b38f9ff09">

**Comment by The-Fireplace** [comment]
Solved with version 7.1.2
